# Generated by Django 5.1.4 on 2025-08-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffeenote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bean', models.CharField(blank=True, max_length=64, verbose_name='豆')),
                ('roast_level', models.CharField(blank=True, max_length=64, verbose_name='焙煎度')),
                ('extract_method', models.CharField(blank=True, max_length=64, verbose_name='抽出方法')),
                ('grind_size', models.CharField(blank=True, max_length=64, verbose_name='挽き方')),
                ('memo', models.CharField(blank=True, max_length=256, verbose_name='メモ')),
                ('smell', models.PositiveIntegerField(default=0, verbose_name='香り')),
                ('acdity', models.PositiveIntegerField(default=0, verbose_name='酸味')),
                ('body', models.PositiveIntegerField(default=0, verbose_name='コク')),
                ('aftertaste', models.PositiveIntegerField(default=0, verbose_name='後味')),
                ('bitterness', models.PositiveIntegerField(default=0, verbose_name='苦味')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop')),
            ],
        ),
    ]
