# Generated by Django 5.1.4 on 2025-08-06 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_mode', models.CharField(choices=[('chroma', 'Chroma'), ('faiss', 'FAISS'), ('pinecone', 'Pinecone')], max_length=15, unique=True)),
                ('vectorstore_name', models.CharField(choices=[('chroma', 'Chroma'), ('faiss', 'FAISS'), ('pinecone', 'Pinecone')], default='chroma', max_length=15)),
                ('vectorstore_path', models.CharField(max_length=255)),
                ('source_document_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('response_mode', models.CharField(blank=True, choices=[('chroma', 'Chroma'), ('faiss', 'FAISS'), ('pinecone', 'Pinecone')], default='free', max_length=15)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
